version: '2'
output: 'prefixed'

tasks:
  build:
    cmds:
        - nasm boot1.asm -f bin -o boot1.bin
        - nasm boot2.asm -f bin -o boot2.bin
        - nasm boot3.asm -f bin -o boot3.bin
        - nasm boot4.asm -f bin -o boot4.bin
  boot1:
    cmds:
     - qemu-system-i386 -hda boot1.bin
  boot2:
    cmds:
     - qemu-system-i386 -hda boot2.bin
  boot3:
    cmds:
     - qemu-system-i386 -hda boot3.bin
  boot4:
    cmds:
     - qemu-system-i386 -hda boot4.bin
